### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by soham2008xyz**
Document how to use a custom Ollama endpoint in README.

This is an extension of #7.

### CODE REVIEW

**Comment by dalisoft** [comment]
@soham2008xyz I think worth adding this way of setting environment variables as other variants (zsh profile, bash profile, fish set did not worket)

```zsh
launchctl setenv NOTESOLLAMA_OLLAMA_BASE_URL "http://YOUR_ENDPOINT_IP:11434"
```

**Comment by dalisoft** [comment]
@andersrex I tried v0.2.5 and it not worked with custom endpoint, i have needed build locally to make it work. Could be nice to see update on your website. Thank you for amazing tool

**Comment by andersrex** [comment]
@dalisoft latest version now has custom endpoint support: https://smallest.app/notesollama/

**Comment by dalisoft** [comment]
Thank you @andersrex

**Pull request merged**
